# Generated by Django 3.0 on 2020-02-03 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horoscope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('content', models.TextField(blank=True)),
                ('image', models.ImageField(default='img.jpg', upload_to='')),
            ],
            options={
                'db_table': 'horoscope',
            },
        ),
    ]
